# Generated by Django 3.0.8 on 2021-10-16 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estudiantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiantes_nomnbre', models.CharField(max_length=150)),
                ('estudiantes_apellido', models.CharField(max_length=150)),
                ('estudiantes_anulado', models.CharField(choices=[('1', 'Activo'), ('0', 'No Activo')], default='1', help_text='Seleccione el Estado', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='materias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materias_nombre', models.CharField(max_length=150)),
                ('materias_anulada', models.CharField(choices=[('1', 'Activo'), ('0', 'No Activo')], default='1', help_text='Seleccione el Estado', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.FloatField()),
                ('id_estudiantes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atcore.estudiantes')),
                ('id_materias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atcore.materias')),
            ],
        ),
    ]
