# Generated by Django 3.0.8 on 2021-10-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atcore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='notasanulado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'No Activo')], default='1', help_text='Seleccione el Estado', max_length=1),
        ),
    ]
